### ISSUE TITLE
Beadando

### ISSUE THREAD

**Issue by nebence15** [Teaching-projects/januari-beadando-nebence15#1]

**Comment by nebence15** [comment]
@hegyhati  Beadtam a végleges változatot

**Comment by hegyhati** [comment]
van ket fuggvenyed, de meg sem hivod oket, a betuket nem irod ki a felhasznalonak, ugynazert a szoert tobbszor is van pont, es csak 5 ponttal lehet befejezni... 
kicsit ugy tunik, mintha egyszer sem probaltad volna ki a programod.... 
2
